experiment_type: 'lrvae'  # lidvae, vae, nae, lrvae 중 선택

common_params:
  exp_data: 'pinwheel'  # mnist, fashionmnist, cifar10, celeba, omniglot, pinwheel, chessboard
  exp_epochs: 1000
  batch_size: 1024
  niter: 1  # 각 설정당 반복 횟수
  logfilename: null
  resultname: null
  # pt_param: 'path/to/pretrained.pt'  # 사전학습된 모델 경로 (선택사항)
  grad_clip:
    enabled: true
    clip_type: 'norm'  # 'norm' or 'value'
    max_norm: 1.0      # used when clip_type == 'norm'
    norm_type: 2.0     # used when clip_type == 'norm'
    clip_value: 1.0    # used when clip_type == 'value'

model_params:
  beta_list: [0.001, 0.01]  # beta 값 리스트
  log_mse: false
  encoder_type: 'mlp'  # conv 또는 mlp
  decoder_type: 'mlp'  # conv 또는 mlp
  fixed_var: false
  residual_connection: false
  hchans: [16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16]  # hidden channels 설정
  num_mc_samples: 1


  # LIDVAE 파라미터
  #il_list: [1.0]  # inverse lipschitz 값 리스트

  # LRVAE 파라미터
  alpha_list: [0.0001]
  # z_source: 'Ex'
  pwise_reg: false
